-- the password hash is generated by BCrypt Calculator Generator(https://www.dailycred.com/article/bcrypt-calculator)
INSERT INTO user (id, username, password, firstname, lastname, email) VALUES (1, 'user', '$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra', 'Fan', 'Jin', 'ceva@gmail.com');
INSERT INTO user (id, username, password, firstname, lastname, email) VALUES (2, 'admin', '$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra', 'Jing', 'Xiao', 'altceva@gmail.com');

INSERT INTO authority (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO authority (id, name) VALUES (2, 'ROLE_ADMIN');

INSERT INTO user_authority (user_id, authority_id) VALUES (1, 1);
INSERT INTO user_authority (user_id, authority_id) VALUES (2, 1);
INSERT INTO user_authority (user_id, authority_id) VALUES (2, 2);


INSERT INTO book (id, title, author, genre,  image) VALUES (1, 'amintiri din copilarie', 'creanga ionica', 'proza', 'path1');
INSERT INTO book (id, title, author, genre,  image) VALUES (2, 'luceafarul ca tot a picat la bac', 'misu eminescu', 'poezie', 'path2');


INSERT INTO borrow(id, book_id, User, beginDate, endDate) values (1, 1, 1, null, null);
INSERT INTO borrow(id, book_id, User, beginDate, endDate) values (2, 2, 1, null, null);
